### ISSUE TITLE
Question on “Writing a Custom Voting Strategy”

### ISSUE THREAD

**Issue by samajammin** [allo-protocol/docs#84]
Hey folks,

Reading through this page:
https://docs.allo.gitcoin.co/strategies/writing-a-custom-strategy

> Fork the [allo-protocol/contracts](https://github.com/allo-protocol/contracts) repo.

Is this the correct repo? Or do we want to use contracts in v2?
https://github.com/allo-protocol/allo-v2

**Comment by codenamejason** [comment]
This is a typo and thanks for flagging. It should link to Allo v2 contracts repo [here](https://github.com/allo-protocol/allo-v2)
